config/routes.rb
GroceryApp::Application.routes.draw do
  resources :lists

  devise_for :users

  resources :items

  resources :sections
  
  match 'first' => 'sections#first'
  match 'list' => 'sections#list'
  root :to => "lists#index"

end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :items, :dependent => :destroy 
  belongs_to :list
  accepts_nested_attributes_for :items, :reject_if => lambda { |a| a[:item_name].blank? }, :allow_destroy => true 
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  # GET /sections
  # GET /sections.xml
  
  before_filter :find_list
  
  def  find_list
  	if  params[:list_id]
  		@list = List.find_by_id(params[:list_id])
  	end
  end
  
  def index
    #@sections = Section.all
    @sections = Section.where(:list_id =>@list.id)
      @section.items.build
      @section.list_id = @list.id

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sections }
    end
  end
  
  def list
    #@sections = Section.all
    @sections = Section.where(:list_id =>@list.id)
    @items = Item.all
     

    respond_to do |format|
      format.html # index.html.erb
      #format.html {redirect_to :controller => "sections", :action => "new" , :list_id=>@list.id}
      
      format.xml  { render :xml => @sections }
    end
  end

  # GET /sections/1
  # GET /sections/1.xml
  def show
    @section = Section.find(params[:id])

    respond_to do |format|
      #format.html {redirect_to :controller => "sections", :action => "new" , :list_id=>@list.id}
      
      format.html # show.html.erb
      format.xml  { render :xml => @section }
    end
  end

  # GET /sections/new
  # GET /sections/new.xml
  def new
    @section = Section.new
    @section.items.build
    @section.list_id = @list.id

    respond_to do |format|
      
      format.html # new.html.erb
      format.xml  { render :xml => @section }
    end
  end
  
  def first
    @section = Section.new
    @section.items.build
    @section.list_id = @list.id

    respond_to do |format|
      
      format.html # new.html.erb
      format.xml  { render :xml => @section }
    end
  end

  # GET /sections/1/edit
  def edit
    @section = Section.find(params[:id])
    @section.list_id = @list.id
  end

  # POST /sections
  # POST /sections.xml
  def create
    @section = Section.new(params[:section])

    respond_to do |format|
      if @section.save
        format.html { redirect_to(@section, :notice => 'Section was successfully created.') }
        format.xml  { render :xml => @section, :status => :created, :location => @section }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @section.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sections/1
  # PUT /sections/1.xml
  def update
    @section = Section.find(params[:id])

    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to(@section, :notice => 'Section was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @section.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.xml
  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to(sections_url) }
      format.xml  { head :ok }
    end
  end
  
  
  
  
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.hidden_field :list_id, :value => @list.id %>
	

  <div class="field">
	<br />
    <%= f.label :section_name %><br />
    <%= f.text_field :section_name %>
  </div>


  <%= f.fields_for :items do |g| %> 

	<%= render "item_fields", :f => g %>

  <% end %>




<p><%= link_to_add_fields "Add Item", f, :items %></p>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/_item_fields.html.erb
    <br />
<div class="fields">	
	<%= f.label :item_name %><br />
    <%= f.text_field :item_name %>
    <%= f.hidden_field :_destroy %>
	<%= link_to_function "remove", "remove_fields(this)" %>
</div>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%#= f.hidden_field :list_id, :value => @list.id %>
	<%= f.hidden_field :list_id, :value => @list.id %>
	

  <div class="field">
	<br />
    <%= f.label :section_name %><br />
    <%= f.text_field :section_name %>
  </div>


  <%= f.fields_for :items do |g| %> 

	<%= render "item_fields", :f => g %>

  <% end %>




<p><%= link_to_add_fields "Add Item", f, :items %></p>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @section %> |
<%= link_to "Back to List", :action => "list", :list_id=>@list.id %>

app/views/sections/first.html.erb
<h1>Start List</h1>

<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.hidden_field :list_id, :value => @list.id %>
	

  <div class="field">
	<br />
    <%= f.label :section_name %><br />
    <%= f.text_field :section_name %>
  </div>


  <%= f.fields_for :items do |g| %> 

	<%= render "item_fields", :f => g %>

  <% end %>




<p><%= link_to_add_fields "Add Item", f, :items %></p>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<%= link_to "Back to List", :action => "list", :list_id=>@list.id %>

app/views/sections/index.html.erb
<h1>Listing sections</h1>

<table>
  <tr>
    <th>Section name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sections.each do |section| %>
  <tr>
    <td><%= section.section_name %></td>
    <td><%= link_to 'Show', section %></td>
    <td><%= link_to 'Edit', edit_section_path(section) %></td>
    <td><%= link_to 'Destroy', section, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Section', new_section_path %><br /><br />
<%= link_to "Back to List", :action => "list" %>

app/views/sections/list.html.erb
<h1>Listing sections</h1>

<table>

<% @sections.each do |section| %>

	<% if section.items.length >= 1 %>
		<tr>
			<td>
			<%= section.section_name %>
			</td>
			<td>
			<%= link_to 'Edit', edit_section_path(section) %>
			</td>
		</tr>
			
				<% @items.each do |item| %>

						  <% if item.section_id == section.id %> 
						<tr>
							<td>
							 	&nbsp;&nbsp;&nbsp;&nbsp;<%= item.item_name %>
							</td>
						    <td>
						     <%= link_to 'Edit', edit_item_path(item), :list_id=>@list.id %>
						    </td>
						</tr>
				 		 <% end %>
					
				<% end %>
	<% end %>
<% end %>
</table>
<%= link_to "New Section", :controller => "sections", :action => "new", :list_id=>@list.id %><br />
<%= link_to "New Item", :controller => "items", :action => "new" %>

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render 'form' %>
<%#= link_to "Back to List", :action => "list", :list_id=>@list.id %>
<%= link_to 'Back to List', lists_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Section name:</b>
  <%= @section.section_name %>
</p>

<b>Items</b>
<ul>
<% @section.items.each do |a| %>
 <% if a.item_name != '' %>
<li><%= a.item_name %></li>
 <% end %>
<% end %>
</ul>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back to List', lists_path %>