config/routes.rb
GroceryApp::Application.routes.draw do
  resources :lists

  devise_for :users

  resources :items

  resources :sections
  
  match 'first' => 'sections#first'
  match 'list' => 'sections#list'
  root :to => "lists#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :section
  accepts_nested_attributes_for :section 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.xml
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @items }
    end
  end

  # GET /items/1
  # GET /items/1.xml
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/new
  # GET /items/new.xml
  def new
    @item = Item.new
    @sections =Section.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
    @sections =Section.all
  end

  # POST /items
  # POST /items.xml
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to(@item, :notice => 'Item was successfully created.') }
        format.xml  { render :xml => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.xml
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to(@item, :notice => 'Item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.xml
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to(items_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if add_section? %>
  <% @item.build_section unless @item.section %>
   <%= f.fields_for :section do |g| %>
    <%= g.label :section_name %><br />
    <%= g.text_field :section_name %><br />
  <% end %>
<% end %>

<% if !add_section? %>
  <div class="field">
    <%= f.collection_select(:section_id, @sections, :id, :section_name) %>
  </div>
<% end %>

  <div class="field">
    <%= f.label :item_name %><br />
    <%= f.text_field :item_name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%#= link_to "Back to List", :controller => "sections", :action => "list" %>
<%= link_to 'Back to List', {:controller => 'sections', :action => 'list', :list_id => list.id } %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Item name</th>
    <th>Section</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
 <% if item.item_name != '' %> 
 <tr>
    <td><%= item.item_name %></td>
    <td><%= item.section.section_name %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
 <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %><br />
<%= link_to "Back to List", :controller => "sections", :action => "list" %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to "Back to List", :controller => "sections", :action => "list" %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Item name:</b>
  <%= @item.item_name %>
</p>

<p>
  <b>Section:</b>
  <%= @item.section.section_name %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to "Back to List", :controller => "sections", :action => "list" %>